---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mark-ingress
  annotations:
    gethomepage.dev/description: "TagsDev | Mark Taguaid | Old-site"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Links
    gethomepage.dev/icon: https://raw.githubusercontent.com/mcbtaguiad/web-tagsdev-django/master/app/app/static/img/favicon.ico
    gethomepage.dev/name: TagsDev
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
      - mark.tagsdev.click
    secretName: mark-tls
  rules:
  - host: mark.tagsdev.click
    http:
      paths:
      - path: /
        #pathType: ImplementationSpecific
        pathType: Prefix
        backend:
          service: 
            name: web-mark
            port:
              number: 8000